name: Build MovieReview Website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore NuGet packages
      run: nuget restore src/MovieReview-Angular/MovieReview.Web.sln

    - name: Build and publish
      run: msbuild src/MovieReview-Angular/MovieReview.Web/MovieReview.Web.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:OutputPath=publish/

    - name: Upload published output
      uses: actions/upload-artifact@v4
      with:
        name: PublishedOutput
        path: src/MovieReview-Angular/MovieReview.Web/obj/Release/Package/PackageTmp/**

  docker:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout repo (for Dockerfile)
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: PublishedOutput
          path: artifact_zip

      - name: Extract build artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path app | Out-Null
          Expand-Archive -Path "artifact_zip\PublishedOutput.zip" -DestinationPath "app" -Force

      - name: List extracted files
        shell: pwsh
        run: Get-ChildItem -Recurse app